### PR TITLE
Single brain hemisphere registration

### PR DESCRIPTION
**Pull request by JulesScholler**
- Add a --brain_geometry flag where user can choose between full brain (default) or one of the hemisphere (right/left)
- The function that computes the volume of each region won't throw a warning when half brain are register and silently write 0
- I corrected a deprecation warning (append method for DataFrame will be removed from pandas and I replaced it with contatenate)

### CODE REVIEW

**Comment by JulesScholler** [comment]
I am not sure what went wrong with the tests, I can modify the PR if you let me know what was wrong.

The SonarCloud is not happy because the 'main' function has 14 arguments, I can refactor but don't want to modify the library too much (might be better to just pass the args dict to function rather than individual args).

**Comment by adamltyson** [comment]
The tests are failing currently because of the linting checks, if you run `black /path/to/dir` it should format the code for you.

**Comment by adamltyson** [comment]
I'm getting a few errors trying to run the tests, but mostly the tests are messed up (the original ones, not yours @JulesScholler). What do you think about getting #67 and #69 merged, then working on this PR. @JulesScholler, @dstansby?

Generally though, this looks great, thanks @JulesScholler!

**Comment by JulesScholler** [comment]
I am fine with this plan, once you merged I can adapt the tests for single hemispheres.

**Comment by dstansby** [comment]
Tests should now be fixed - if you rebase on to the current `master` branch then CI should run for you.

**Comment by JulesScholler** [comment]
Tests are still failing, I have no time to fix this.

**Pull request merged**
