### PR TITLE
Update brainglobe-napari-io import

### PR DESCRIPTION
**Pull request by adamltyson**
Requires https://github.com/brainglobe/brainglobe-napari-io/pull/61 to be merged (tests will fail until it's released), and when a new version is released, it will need to pin the latest version of `brainglobe-napari-io`.

### CODE REVIEW

**Review by alessandrofelder — DISMISSED** [review]
👍 
Given that the new `brainglobe-napari-io` is released, should we pin the version in this PR (and then merge and release)?

**Comment by willGraham01** [comment]
@alessandrofelder sorry for the dismissal I was only following your recommendation :joy: But have now pinned the new version in this update.

**Review by alessandrofelder — APPROVED** [review]

**Comment by alessandrofelder** [comment]
> I think it's important we always pin new versions in the pull requests. The meta-package should handle them ...

The metapackage (at least its user-facing part, not the future benchmarks that will depend on the dev version) will only install released versions, right. So should this technically be

> I think it's important we always pin new versions before releasing?

?

**Comment by adamltyson** [comment]
Pinning (the minimum) version is always probably a good idea though right, so that `pip install brainglobe -U` will fetch the correct packages.

**Pull request merged**
